//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int QuestionId { get; set; }
        public string OptionIndex { get; set; }
        public string OptionText { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
