//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Options = new HashSet<Option>();
        }
    
        public Nullable<int> SubjectId { get; set; }
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
    }
}
