//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int TestId { get; set; }
        public string TestName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
    }
}
